project '/Users/sqiyan/Desktop/LYNC/XcodeFixTest/Lyncv2/Lyncv2.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lyncv2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lyncv2

  target 'Lyncv2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Lyncv2UITests' do
    # Pods for testing
  end

end
